// <auto-generated />
using System;
using Admision.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Admision.Infraestructura.Migrations
{
    [DbContext(typeof(ContextoBaseDeDatos))]
    [Migration("20260625030922_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Admision.Dominio.Entidades.Cama", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Camas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-cccc-cccc-cccc-333333333333"),
                            Estado = "Ocupada",
                            Numero = 201,
                            SectorId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("55555555-eeee-eeee-eeee-555555555555"),
                            Estado = "Disponible",
                            Numero = 202,
                            SectorId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("33333333-0203-cccc-cccc-333333333333"),
                            Estado = "Disponible",
                            Numero = 203,
                            SectorId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("33333333-0204-cccc-cccc-333333333333"),
                            Estado = "Disponible",
                            Numero = 204,
                            SectorId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("33333333-0205-cccc-cccc-333333333333"),
                            Estado = "Disponible",
                            Numero = 205,
                            SectorId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("33333333-0206-cccc-cccc-333333333333"),
                            Estado = "Disponible",
                            Numero = 206,
                            SectorId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("33333333-0207-cccc-cccc-333333333333"),
                            Estado = "Disponible",
                            Numero = 207,
                            SectorId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("33333333-0208-cccc-cccc-333333333333"),
                            Estado = "Disponible",
                            Numero = 208,
                            SectorId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("33333333-0209-cccc-cccc-333333333333"),
                            Estado = "Disponible",
                            Numero = 209,
                            SectorId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("33333333-0210-cccc-cccc-333333333333"),
                            Estado = "Disponible",
                            Numero = 210,
                            SectorId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("44444444-dddd-dddd-dddd-444444444444"),
                            Estado = "Ocupada",
                            Numero = 101,
                            SectorId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("66666666-aaaa-aaaa-aaaa-666666666666"),
                            Estado = "Disponible",
                            Numero = 102,
                            SectorId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("44444444-0103-dddd-dddd-444444444444"),
                            Estado = "Disponible",
                            Numero = 103,
                            SectorId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("44444444-0104-dddd-dddd-444444444444"),
                            Estado = "Disponible",
                            Numero = 104,
                            SectorId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("44444444-0105-dddd-dddd-444444444444"),
                            Estado = "Disponible",
                            Numero = 105,
                            SectorId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("44444444-0106-dddd-dddd-444444444444"),
                            Estado = "Disponible",
                            Numero = 106,
                            SectorId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("44444444-0107-dddd-dddd-444444444444"),
                            Estado = "Disponible",
                            Numero = 107,
                            SectorId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("44444444-0108-dddd-dddd-444444444444"),
                            Estado = "Disponible",
                            Numero = 108,
                            SectorId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("44444444-0109-dddd-dddd-444444444444"),
                            Estado = "Disponible",
                            Numero = 109,
                            SectorId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("44444444-0110-dddd-dddd-444444444444"),
                            Estado = "Disponible",
                            Numero = 110,
                            SectorId = new Guid("88888888-8888-8888-8888-888888888888")
                        });
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Internacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaEgreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Internaciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-ffff-ffff-ffff-666666666666"),
                            Estado = "Activa",
                            FechaIngreso = new DateTime(2026, 6, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Motivo = "Ingreso por guardia con cuadro respiratorio agudo.",
                            PacienteId = new Guid("11111111-aaaa-aaaa-aaaa-111111111111")
                        },
                        new
                        {
                            Id = new Guid("77777777-1111-1111-1111-777777777777"),
                            Estado = "Activa",
                            FechaIngreso = new DateTime(2026, 6, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            Motivo = "Control evolutivo post-cirugía.",
                            PacienteId = new Guid("22222222-bbbb-bbbb-bbbb-222222222222")
                        });
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.InternacionCama", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CamaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaIngresoCama")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSalidaCama")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InternacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotivoTraslado")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CamaId");

                    b.HasIndex("InternacionId");

                    b.ToTable("InternacionesCamas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-2222-2222-2222-888888888888"),
                            CamaId = new Guid("33333333-cccc-cccc-cccc-333333333333"),
                            EsActual = true,
                            FechaIngresoCama = new DateTime(2026, 6, 15, 8, 30, 0, 0, DateTimeKind.Utc),
                            InternacionId = new Guid("66666666-ffff-ffff-ffff-666666666666")
                        },
                        new
                        {
                            Id = new Guid("99999999-3333-3333-3333-999999999999"),
                            CamaId = new Guid("44444444-dddd-dddd-dddd-444444444444"),
                            EsActual = true,
                            FechaIngresoCama = new DateTime(2026, 6, 16, 10, 30, 0, 0, DateTimeKind.Utc),
                            InternacionId = new Guid("77777777-1111-1111-1111-777777777777")
                        });
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("Pacientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-aaaa-aaaa-aaaa-111111111111"),
                            Dni = "21123456",
                            FechaNacimiento = new DateTime(1971, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Carlos Mendoza",
                            Sexo = "Masculino",
                            Telefono = "11-4444-5555"
                        },
                        new
                        {
                            Id = new Guid("22222222-bbbb-bbbb-bbbb-222222222222"),
                            Dni = "22123456",
                            FechaNacimiento = new DateTime(1972, 10, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Luciana Gómez",
                            Sexo = "Femenino",
                            Telefono = "11-2222-3333"
                        },
                        new
                        {
                            Id = new Guid("33333333-2373-cccc-cccc-333333333333"),
                            Dni = "23123456",
                            FechaNacimiento = new DateTime(1973, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Roberto Sánchez",
                            Sexo = "Masculino",
                            Telefono = "11-9999-8888"
                        },
                        new
                        {
                            Id = new Guid("44444444-2474-dddd-dddd-444444444444"),
                            Dni = "24123456",
                            FechaNacimiento = new DateTime(1974, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "María Fernández",
                            Sexo = "Femenino",
                            Telefono = "11-7777-6666"
                        },
                        new
                        {
                            Id = new Guid("55555555-2575-eeee-eeee-555555555555"),
                            Dni = "25123456",
                            FechaNacimiento = new DateTime(1975, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Javier Rodríguez",
                            Sexo = "Masculino",
                            Telefono = "11-5555-4444"
                        },
                        new
                        {
                            Id = new Guid("66666666-2676-ffff-ffff-666666666666"),
                            Dni = "26123456",
                            FechaNacimiento = new DateTime(1976, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Silvana López",
                            Sexo = "Femenino",
                            Telefono = "11-3333-2222"
                        },
                        new
                        {
                            Id = new Guid("77777777-2777-aaaa-aaaa-777777777777"),
                            Dni = "27123456",
                            FechaNacimiento = new DateTime(1977, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Diego Martínez",
                            Sexo = "Masculino",
                            Telefono = "11-1111-0000"
                        },
                        new
                        {
                            Id = new Guid("88888888-2878-bbbb-bbbb-888888888888"),
                            Dni = "28123456",
                            FechaNacimiento = new DateTime(1978, 9, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Valeria Torres",
                            Sexo = "Femenino",
                            Telefono = "11-0000-1111"
                        },
                        new
                        {
                            Id = new Guid("99999999-2979-cccc-cccc-999999999999"),
                            Dni = "29123456",
                            FechaNacimiento = new DateTime(1979, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Gustavo Romero",
                            Sexo = "Masculino",
                            Telefono = "11-2222-1111"
                        },
                        new
                        {
                            Id = new Guid("10101010-3080-dddd-dddd-101010101010"),
                            Dni = "30123456",
                            FechaNacimiento = new DateTime(1980, 12, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Natalia Silva",
                            Sexo = "Femenino",
                            Telefono = "11-3333-5555"
                        });
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Piso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sectores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Nombre = "Terapia Intensiva (UTI)",
                            Piso = 2
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Nombre = "Guardia Clínica",
                            Piso = 1
                        });
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Cama", b =>
                {
                    b.HasOne("Admision.Dominio.Entidades.Sector", "Sector")
                        .WithMany("Camas")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Internacion", b =>
                {
                    b.HasOne("Admision.Dominio.Entidades.Paciente", "Paciente")
                        .WithMany("Internaciones")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.InternacionCama", b =>
                {
                    b.HasOne("Admision.Dominio.Entidades.Cama", "Cama")
                        .WithMany("HistorialInternaciones")
                        .HasForeignKey("CamaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Admision.Dominio.Entidades.Internacion", "Internacion")
                        .WithMany("HistorialCamas")
                        .HasForeignKey("InternacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cama");

                    b.Navigation("Internacion");
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Cama", b =>
                {
                    b.Navigation("HistorialInternaciones");
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Internacion", b =>
                {
                    b.Navigation("HistorialCamas");
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Paciente", b =>
                {
                    b.Navigation("Internaciones");
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Sector", b =>
                {
                    b.Navigation("Camas");
                });
#pragma warning restore 612, 618
        }
    }
}
