// <auto-generated />
using System;
using Admision.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Admision.Infraestructura.Migrations
{
    [DbContext(typeof(ContextoBaseDeDatos))]
    partial class ContextoBaseDeDatosModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Admision.Dominio.Entidades.Cama", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Camas", (string)null);
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Internacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEgreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Internaciones", (string)null);
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.InternacionCama", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CamaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaIngresoCama")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSalidaCama")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InternacionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CamaId");

                    b.HasIndex("InternacionId");

                    b.ToTable("InternacionesCamas", (string)null);
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Piso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sectores", (string)null);
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Cama", b =>
                {
                    b.HasOne("Admision.Dominio.Entidades.Sector", "Sector")
                        .WithMany("Camas")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Internacion", b =>
                {
                    b.HasOne("Admision.Dominio.Entidades.Paciente", "Paciente")
                        .WithMany("Internaciones")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.InternacionCama", b =>
                {
                    b.HasOne("Admision.Dominio.Entidades.Cama", "Cama")
                        .WithMany("HistorialInternaciones")
                        .HasForeignKey("CamaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Admision.Dominio.Entidades.Internacion", "Internacion")
                        .WithMany("HistorialCamas")
                        .HasForeignKey("InternacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cama");

                    b.Navigation("Internacion");
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Cama", b =>
                {
                    b.Navigation("HistorialInternaciones");
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Internacion", b =>
                {
                    b.Navigation("HistorialCamas");
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Paciente", b =>
                {
                    b.Navigation("Internaciones");
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Sector", b =>
                {
                    b.Navigation("Camas");
                });
#pragma warning restore 612, 618
        }
    }
}
