// <auto-generated />
using System;
using Admision.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Admision.Infraestructura.Migrations
{
    [DbContext(typeof(ContextoBaseDeDatos))]
    partial class ContextoBaseDeDatosModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Admision.Dominio.Entidades.Cama", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Camas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-cccc-cccc-cccc-333333333333"),
                            Estado = "Ocupada",
                            Numero = 101,
                            SectorId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("44444444-dddd-dddd-dddd-444444444444"),
                            Estado = "Ocupada",
                            Numero = 201,
                            SectorId = new Guid("88888888-8888-8888-8888-888888888888")
                        },
                        new
                        {
                            Id = new Guid("55555555-eeee-eeee-eeee-555555555555"),
                            Estado = "Disponible",
                            Numero = 102,
                            SectorId = new Guid("99999999-9999-9999-9999-999999999999")
                        });
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Internacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaEgreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Internaciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-ffff-ffff-ffff-666666666666"),
                            Estado = "Activa",
                            FechaIngreso = new DateTime(2026, 6, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Motivo = "Ingreso por guardia con cuadro respiratorio agudo.",
                            PacienteId = new Guid("11111111-aaaa-aaaa-aaaa-111111111111")
                        },
                        new
                        {
                            Id = new Guid("77777777-1111-1111-1111-777777777777"),
                            Estado = "Activa",
                            FechaIngreso = new DateTime(2026, 6, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            Motivo = "Control evolutivo post-cirugía.",
                            PacienteId = new Guid("22222222-bbbb-bbbb-bbbb-222222222222")
                        });
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.InternacionCama", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CamaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaIngresoCama")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSalidaCama")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InternacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotivoTraslado")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CamaId");

                    b.HasIndex("InternacionId");

                    b.ToTable("InternacionesCamas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-2222-2222-2222-888888888888"),
                            CamaId = new Guid("33333333-cccc-cccc-cccc-333333333333"),
                            EsActual = true,
                            FechaIngresoCama = new DateTime(2026, 6, 15, 8, 30, 0, 0, DateTimeKind.Utc),
                            InternacionId = new Guid("66666666-ffff-ffff-ffff-666666666666")
                        },
                        new
                        {
                            Id = new Guid("99999999-3333-3333-3333-999999999999"),
                            CamaId = new Guid("44444444-dddd-dddd-dddd-444444444444"),
                            EsActual = true,
                            FechaIngresoCama = new DateTime(2026, 6, 16, 10, 30, 0, 0, DateTimeKind.Utc),
                            InternacionId = new Guid("77777777-1111-1111-1111-777777777777")
                        });
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("Pacientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-aaaa-aaaa-aaaa-111111111111"),
                            Dni = "25444333",
                            FechaNacimiento = new DateTime(1980, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Carlos Mendoza",
                            Sexo = "Masculino",
                            Telefono = "11-4444-5555"
                        },
                        new
                        {
                            Id = new Guid("22222222-bbbb-bbbb-bbbb-222222222222"),
                            Dni = "30111222",
                            FechaNacimiento = new DateTime(1992, 10, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Luciana Gómez",
                            Sexo = "Femenino",
                            Telefono = "11-2222-3333"
                        });
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Piso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sectores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Nombre = "Terapia Intensiva (UTI)",
                            Piso = 2
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Nombre = "Guardia Clínica",
                            Piso = 1
                        });
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Cama", b =>
                {
                    b.HasOne("Admision.Dominio.Entidades.Sector", "Sector")
                        .WithMany("Camas")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Internacion", b =>
                {
                    b.HasOne("Admision.Dominio.Entidades.Paciente", "Paciente")
                        .WithMany("Internaciones")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.InternacionCama", b =>
                {
                    b.HasOne("Admision.Dominio.Entidades.Cama", "Cama")
                        .WithMany("HistorialInternaciones")
                        .HasForeignKey("CamaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Admision.Dominio.Entidades.Internacion", "Internacion")
                        .WithMany("HistorialCamas")
                        .HasForeignKey("InternacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cama");

                    b.Navigation("Internacion");
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Cama", b =>
                {
                    b.Navigation("HistorialInternaciones");
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Internacion", b =>
                {
                    b.Navigation("HistorialCamas");
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Paciente", b =>
                {
                    b.Navigation("Internaciones");
                });

            modelBuilder.Entity("Admision.Dominio.Entidades.Sector", b =>
                {
                    b.Navigation("Camas");
                });
#pragma warning restore 612, 618
        }
    }
}
